"""Domain objects for the autonomous planner."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any


@dataclass
class PlannedTask:
    """A task generated by the planner before becoming a true SubTask."""

    task_id: str
    title: str
    objective: str
    role: str
    dependencies: list[str] = field(default_factory=list)
    success_criteria: list[str] = field(default_factory=list)
    workspace_scope: str = "project"
    priority: int = 5
    model_policy: str = "auto"
    expected_artifacts: list[str] = field(default_factory=list)
    resources: list[dict[str, str]] = field(default_factory=list)
    # Phase 9: requirements this task implements (proposed by the planner as
    # strings like "REQ-001"; the runtime validates & records the mapping).
    traceable_to: list[str] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> PlannedTask:
        return cls(
            task_id=data.get("task_id", ""),
            title=data.get("title", ""),
            objective=data.get("objective", ""),
            role=data.get("role", ""),
            dependencies=data.get("dependencies", []),
            success_criteria=data.get("success_criteria", []),
            workspace_scope=data.get("workspace_scope", "project"),
            priority=data.get("priority", 5),
            model_policy=data.get("model_policy", "auto"),
            expected_artifacts=data.get("expected_artifacts", []),
            resources=data.get("resources", []),
            traceable_to=list(data.get("traceable_to", [])),
        )


@dataclass
class Plan:
    """A collection of planned tasks representing an execution graph."""

    tasks: list[PlannedTask] = field(default_factory=list)
    summary: str = ""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Plan:
        return cls(
            tasks=[PlannedTask.from_dict(t) for t in data.get("tasks", [])],
            summary=data.get("summary", ""),
        )

    @classmethod
    def from_json(cls, json_str: str) -> Plan:
        """Parse JSON into a Plan."""
        data = json.loads(json_str)
        return cls.from_dict(data)


@dataclass
class PlanningConstraint:
    """Constraints passed to the planner."""

    available_roles: list[str] = field(default_factory=list)
    available_tools: list[str] = field(default_factory=list)


@dataclass
class PlanningResult:
    """Result of a planning operation."""

    plan: Plan | None = None
    success: bool = False
    errors: list[str] = field(default_factory=list)
    raw_response: str = ""
